export const gbps = [
  {
    clientId: '1',
    companyName: 'Tech Solutions Ltd.',
    bussinessType: 'IT Services',
    email: 'info@techsolutions.com',
    bussinessCategory: 'Information Technology',
    servicesArea: 'Global',
    phoneNumber: '+1-800-555-1234',
    website: 'https://www.techsolutions.com',
    country: 'United States',
    city: 'New York',
    state: 'New York',
    address: '123 Tech Avenue, Suite 100',
    postalCode: '10001',
    additionalServices: 'Cloud Solutions, Data Analysis, Cybersecurity',
    schedules: 'Mon-Fri 9:00 AM - 6:00 PM',
    largeDescription:
      'Tech Solutions Ltd. offers innovative technology solutions to help businesses streamline operations and stay ahead in a competitive digital landscape. We specialize in cloud computing, data management, and IT consulting.',
    pinterest: 'https://pinterest.com/techsolutions',
    tiktok: 'https://tiktok.com/@techsolutions',
    linkedin: 'https://linkedin.com/company/techsolutions',
    instagram: 'https://instagram.com/techsolutions',
    facebook: 'https://facebook.com/techsolutions',
    twitter: 'https://twitter.com/techsolutions',
    youtube: 'https://youtube.com/techsolutions',
    shortDescription: 'Leading provider of IT solutions and services.',
    customersOpinions:
      'Our clients appreciate the fast, reliable service and the strategic advice we provide for their technology needs.',
    featuredProperties:
      'Cutting-edge technology, highly skilled team, and global presence.',
    appointmentsContacts:
      'For consultations, email us at appointments@techsolutions.com or call +1-800-555-1234.',
    relatedAgencies: 'Partnered with Microsoft, AWS, Google Cloud',
    paymentMethods: 'Credit Card, PayPal, Wire Transfer',
    hashtags: '#ITservices #TechSolutions #CloudComputing',
    keywords: 'IT services, Cloud solutions, Cybersecurity, Data Analysis',
    slongan: 'Empowering businesses through technology.',
    startOperations: '2010',
    certification: 'ISO 27001, Microsoft Gold Partner, AWS Certified',
    positions: 'CEO, CTO, IT Consultant, Project Manager',
    description:
      'We deliver advanced IT services to businesses worldwide, helping them grow and secure their operations through cutting-edge technology.',
    createdAt: '2024-01-15',
  },
];
