export const gbp = [
  {
    companyName: 'John Doe',
    bussinessType: 'John Doe',
    email: 'G4I6W@example.com',
    bussinessCategory: 'John Doe',
    servicesArea: 'John Doe',
    phoneNumber: 'John Doe',
    website: 'John Doe',
    country: 'John Doe',
    city: 'John Doe',
    state: 'John Doe',
    address: 'John Doe',
    postalCode: 'John Doe',
    additionalServices: 'John Doe',
    schedules: 'John Doe',
    largeDescription: 'John Doe',
    pinterest: 'John Doe',
    tiktok: 'John Doe',
    linkedin: 'John Doe',
    instagram: 'John Doe',
    facebook: 'John Doe',
    twitter: 'John Doe',
    youtube: 'John Doe',
    shortDescription: 'John Doe',
    customersOpinions: 'John Doe',
    featuredProperties: 'John Doe',
    appointmentsContacts: 'John Doe',
    relatedAgencies: 'John Doe',
    paymentMethods: 'John Doe',
    hashtags: 'John Doe',
    keywords: 'John Doe',
    slongan: 'John Doe',
    startOperations: 'John Doe',
    certification: 'John Doe',
    positions: 'John Doe',
    description: 'John Doe',
    createdAt: 'John Doe',
  },
];
