import { z } from 'zod';

export const gbpFormSchema = z.object({
  id: z.string().uuid(),
  clientId: z.string().uuid('Ingrese un id de cliente válido'),
  companyName: z.string().min(1, 'Ingrese un nombre'),
  bussinessType: z.string().min(1, 'Ingrese un tipo de negocios'),
  email: z.string().email('Ingrese un correo electrónico'),
  bussinessCategory: z.string().min(1, 'Ingrese una categoria negocios'),
  servicesArea: z.string().min(1, 'Ingrese una area de servicio'),
  phoneNumber: z.coerce
    .string()
    .min(0, 'Ingrese un número igual o mayor a cero'),
  website: z.string().url('Ingrese un sitio web'),
  country: z.string().min(1, 'Ingrese un pais'),
  city: z.string().min(1, 'Ingrese una ciudad'),
  state: z.string().min(1, 'Ingrese un estado'),
  address: z.string().min(1, 'Ingrese una direccion'),
  postalCode: z.string().min(1, 'Ingrese un Codigo postal'),
  additionalServices: z.string().min(1, 'Ingrese los servicios adicionales'),
  schedules: z.string().min(1, 'Ingrese los horarios'),
  largeDescription: z.string().min(1, 'Ingrese una descripción larga'),
  pinterest: z.string().url('Ingrese un link de pinterest'),
  tiktok: z.string().url('Ingrese un link de tiktok'),
  linkedin: z.string().url('Ingrese un link de linkedin'),
  instagram: z.string().url('Ingrese un link de instagram'),
  facebook: z.string().url('Ingrese un link de facebook'),
  twitter: z.string().url('Ingrese un link de twitter'),
  youtube: z.string().url('Ingrese un link de youtube'),
  shortDescription: z.string().min(1, 'Ingrese una descripción corta'),
  customersOpinions: z.string().min(1, 'Ingrese opiniones de clientes'),
  featuredProperties: z.string().min(1, 'Ingrese propiedades destacadas'),
  appointmentsContacts: z.string().min(1, 'Ingrese contactos de citas'),
  relatedAgencies: z.string().min(1, 'Ingrese agencias relacionadas'),
  paymentMethods: z.string().min(1, 'Ingrese metodos de pago'),
  hashtags: z.string().min(1, 'Ingrese hashtags'),
  keywords: z.string().min(1, 'Ingrese keywords'),
  slongan: z.string().min(1, 'Ingrese slongan'),
  startOperations: z.string().min(1, 'Ingrese fecha de apertura'),
  certification: z.string().min(1, 'Ingrese certificación'),
  positions: z.string().min(1, 'Ingrese posiciones'),
  description: z.string().min(1, 'Ingrese una descripción'),
  createdAt: z.string(),
});

export type GbpFormSchema = z.infer<typeof gbpFormSchema>;
